Algoritmo "repita condicional "

Var

   soma, valorA, valorB,:inteiro
   media: real
   resp : caractere

Inicio
   repita
      escreva (" Qual numero deseja digitar?")
      leia (valorA)
      escreva ("Qual sera o outro numero ?")
      leia (valorB)
      media<- ( valorA + valorB)/2
      escreva ( " A media desses mumeros é igual á:", :4:2)
      escreva ( "deseja continuar?(s ou n ")
      
      leia (resp)
      escreval
      ate resp= "n"




Fimalgoritmo