Algoritmo "teste"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2021
Var
// Seção de Declarações das variáveis 
                         largura, comprimento, area  : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       largura <- 50
       comprimento <- 40
       area <- largura * comprimento
       escreva (area )

Fimalgoritmo